### ISSUE TITLE
Release date is wrong

### ISSUE THREAD

**Issue by benkasminbullock** [perlancar/perl-Color-RGB-Util#5]
The release date reads as follows: 

> This document describes version 0.604 of Color::RGB::Util (from Perl distribution Color-RGB-Util), released on 2021-01-19.

Is it automatically generated?

**Comment by perlancar** [comment]
Sorry for the late response, didn't see the notification.

The release date uses the build date. But nowadays I don't immediately release some of my distros (read: upload them to PAUSE), sometimes elapsing weeks between build date and upload date, usually for low-priority releases. The reason is participating in daily CPAN Once-A.
